import { readFileSync, readdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it, vi } from "vitest";

import {
  API_VERSION,
  MiniAppApiError,
  createMiniAppClient,
  getStructuredResult,
  isDecodeResult,
  isDeliveryResponse,
  isHelpSayResult,
  isConsentRequiredError,
  isMiniAppApiError,
  isSoftenResult,
  isWorkflowName,
  toErrorStatus,
  workflowNameValues,
  type DeliveryResponse,
  type MiniAppClientOptions,
} from "../src";

const here = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(here, "../../..");
const FIXTURES = resolve(ROOT, "docs/fixtures");

function fixture<T = unknown>(name: string): T {
  return JSON.parse(readFileSync(resolve(FIXTURES, name), "utf-8")) as T;
}

type Call = { url: string; init: RequestInit };

function mockFetch(responder: (call: Call) => Response) {
  const calls: Call[] = [];
  const fn = vi.fn(async (input: RequestInfo | URL, init?: RequestInit) => {
    const call = { url: String(input), init: init ?? {} };
    calls.push(call);
    return responder(call);
  });
  return { fetch: fn as unknown as typeof fetch, calls };
}

const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), { status, headers: { "Content-Type": "application/json" } });

describe("generated types", () => {
  const spec = JSON.parse(readFileSync(resolve(ROOT, "docs/openapi.json"), "utf-8"));

  it("are generated by openapi-typescript from docs/openapi.json", () => {
    const generated = readFileSync(resolve(here, "../src/generated/openapi.ts"), "utf-8");
    expect(generated).toContain("This file was auto-generated by openapi-typescript.");
    for (const name of Object.keys(spec.components.schemas)) {
      expect(generated).toContain(`${name}: `);
    }
  });

  it("keep handwritten runtime constants in sync with the contract", () => {
    expect(API_VERSION).toBe(spec.info.version);
    expect([...workflowNameValues]).toEqual(spec.components.schemas.WorkflowName.enum);
  });
});

describe("createMiniAppClient", () => {
  it("sends initData header, JSON body and absolute URL with base", async () => {
    const { fetch, calls } = mockFetch(() => json(fixture("relationship.json"), 201));
    const client = createMiniAppClient({ getInitData: () => "raw_init", baseUrl: "https://api.example.com/", fetch });

    const rel = await client.createRelationship({ relation_type: "spouse", aliases: ["Аня"], set_as_default: true });

    expect(rel.relationship_id).toBe("rel_7f3c2a9e");
    expect(calls).toHaveLength(1);
    const [call] = calls;
    expect(call!.url).toBe("https://api.example.com/v1/miniapp/relationships");
    expect(call!.init.method).toBe("POST");
    const headers = call!.init.headers as Record<string, string>;
    expect(headers["X-Telegram-Init-Data"]).toBe("raw_init");
    expect(headers["Content-Type"]).toBe("application/json");
    expect(JSON.parse(String(call!.init.body))).toEqual({
      relation_type: "spouse",
      aliases: ["Аня"],
      set_as_default: true,
    });
  });

  it("uses same-origin relative URLs by default and resolves base lazily", async () => {
    let base = "";
    const { fetch, calls } = mockFetch(() => json(fixture("bootstrap_without_default.json")));
    const client = createMiniAppClient({ getInitData: () => "x", baseUrl: () => base, fetch });

    await client.bootstrap();
    base = "https://late.example.com";
    await client.bootstrap();

    expect(calls.map((c) => c.url)).toEqual([
      "/v1/miniapp/bootstrap",
      "https://late.example.com/v1/miniapp/bootstrap",
    ]);
  });

  it("supports async initData providers", async () => {
    const { fetch, calls } = mockFetch(() => json(fixture("bootstrap_with_default.json")));
    const client = createMiniAppClient({ getInitData: async () => "async_init", baseUrl: "", fetch });

    const data = await client.bootstrap();

    expect(data.user.default_relationship_id).toBe("rel_7f3c2a9e");
    expect((calls[0]!.init.headers as Record<string, string>)["X-Telegram-Init-Data"]).toBe("async_init");
  });

  it("rejects with 401 without calling fetch when initData is missing", async () => {
    const { fetch, calls } = mockFetch(() => json({}));
    const client = createMiniAppClient({ getInitData: () => null, baseUrl: "", fetch });

    await expect(client.bootstrap()).rejects.toMatchObject({ status: 401, detail: "Missing Telegram initData" });
    expect(calls).toHaveLength(0);
  });

  it("maps every endpoint to the documented method and path", async () => {
    const { fetch, calls } = mockFetch(({ init }) =>
      init.method === "DELETE" ? new Response(null, { status: 204 }) : json({}),
    );
    const client = createMiniAppClient({ getInitData: () => "x", baseUrl: "", fetch });

    await client.auth();
    await client.bootstrap();
    await client.listRelationships();
    await client.createRelationship({});
    await client.updateRelationship("r1", { aliases: null });
    await client.deleteRelationship("r1");
    await client.setDefaultRelationship("r1");
    await client.addRule("r1", { type: "avoid", value: "v" });
    await client.updateRule("r1", 7, { type: "avoid", value: "v" });
    await client.deleteRule("r1", 7);
    await client.assist("help-say", { text: "hi" });

    expect(calls.map((c) => `${c.init.method} ${c.url}`)).toEqual([
      "POST /v1/miniapp/auth",
      "GET /v1/miniapp/bootstrap",
      "GET /v1/miniapp/relationships",
      "POST /v1/miniapp/relationships",
      "PATCH /v1/miniapp/relationships/r1",
      "DELETE /v1/miniapp/relationships/r1",
      "PUT /v1/miniapp/me/default-relationship/r1",
      "POST /v1/miniapp/relationships/r1/rules",
      "PUT /v1/miniapp/relationships/r1/rules/7",
      "DELETE /v1/miniapp/relationships/r1/rules/7",
      "POST /v1/miniapp/assist/help-say",
    ]);
  });

  it("encodes path segments", async () => {
    const { fetch, calls } = mockFetch(() => json({}));
    const client = createMiniAppClient({ getInitData: () => "x", baseUrl: "", fetch });

    await client.setDefaultRelationship("a/b c");

    expect(calls[0]!.url).toBe("/v1/miniapp/me/default-relationship/a%2Fb%20c");
  });

  it("returns undefined for 204 responses", async () => {
    const { fetch } = mockFetch(() => new Response(null, { status: 204 }));
    const client = createMiniAppClient({ getInitData: () => "x", baseUrl: "", fetch });

    await expect(client.deleteRule("r1", 1)).resolves.toBeUndefined();
  });

  it.each([
    [401, "error_401.json"],
    [404, "error_404.json"],
    [503, "error_503.json"],
  ])("maps %i error fixtures to MiniAppApiError", async (status, name) => {
    const body = fixture<{ detail: string }>(name);
    const { fetch } = mockFetch(() => json(body, status));
    const client = createMiniAppClient({ getInitData: () => "x", baseUrl: "", fetch });

    const err = await client.bootstrap().catch((e: unknown) => e);

    expect(isMiniAppApiError(err)).toBe(true);
    expect(err).toMatchObject({ status, detail: body.detail, body });
    expect(toErrorStatus(err)).toBe(status);
  });

  it("maps 422 validation errors to a structured list", async () => {
    const body = { detail: [{ loc: ["body", "text"], msg: "Field required", type: "missing" }] };
    const { fetch } = mockFetch(() => json(body, 422));
    const client = createMiniAppClient({ getInitData: () => "x", baseUrl: "", fetch });

    const err = (await client.assist("soften", { text: "" }).catch((e: unknown) => e)) as MiniAppApiError;

    expect(err.isValidationError).toBe(true);
    expect(err.detail).toBe("Request validation failed");
    expect(err.validationErrors).toEqual(body.detail);
  });

  it("falls back to a generic detail for non-JSON error bodies", async () => {
    const { fetch } = mockFetch(() => new Response("<html>", { status: 502 }));
    const client = createMiniAppClient({ getInitData: () => "x", baseUrl: "", fetch });

    await expect(client.bootstrap()).rejects.toMatchObject({ status: 502, detail: "Request failed" });
  });

  it("propagates network failures as TypeError (status 0)", async () => {
    const fetch = vi.fn(async () => {
      throw new TypeError("Failed to fetch");
    }) as unknown as typeof globalThis.fetch;
    const client = createMiniAppClient({ getInitData: () => "x", baseUrl: "", fetch });

    const err = await client.bootstrap().catch((e: unknown) => e);

    expect(err).toBeInstanceOf(TypeError);
    expect(toErrorStatus(err)).toBe(0);
    expect(toErrorStatus(new Error("boom"))).toBe(500);
  });

  it("throws for relative API paths", async () => {
    const client = createMiniAppClient({ getInitData: () => "x", baseUrl: "", fetch: mockFetch(() => json({})).fetch });

    await expect(client.request("v1/miniapp/bootstrap")).rejects.toThrow("API path must start with '/'");
  });

  it("requires injected fetch and getInitData (no global fallback)", () => {
    const fetch = mockFetch(() => json({})).fetch;
    expect(() =>
      createMiniAppClient({ getInitData: () => "x", baseUrl: "" } as unknown as MiniAppClientOptions),
    ).toThrow("fetch must be provided");
    expect(() =>
      createMiniAppClient({ baseUrl: "", fetch } as unknown as MiniAppClientOptions),
    ).toThrow("getInitData must be a function");
  });

  it("never touches globalThis.fetch", async () => {
    const globalFetch = vi.fn();
    vi.stubGlobal("fetch", globalFetch);
    try {
      const { fetch, calls } = mockFetch(() => json({ ok: true }));
      await createMiniAppClient({ getInitData: () => "x", baseUrl: "", fetch }).bootstrap();
      expect(calls).toHaveLength(1);
      expect(globalFetch).not.toHaveBeenCalled();
    } finally {
      vi.unstubAllGlobals();
    }
  });

  it("source does not reference runtime-specific globals", () => {
    for (const file of readdirSync(resolve(here, "../src")).filter((f) => f.endsWith(".ts"))) {
      const source = readFileSync(resolve(here, "../src", file), "utf-8");
      expect(source, file).not.toMatch(/\b(window|globalThis|process|document|import\.meta|Telegram\.WebApp)\b/);
    }
  });
});

describe("guards", () => {
  it("recognises workflow names", () => {
    expect(["soften", "decode", "help-say"].every(isWorkflowName)).toBe(true);
    expect(isWorkflowName("other")).toBe(false);
    expect(isWorkflowName(1)).toBe(false);
  });

  const deliveryFixtures = readdirSync(FIXTURES).filter((n) => n.startsWith("delivery_"));

  it.each(deliveryFixtures)("%s is a DeliveryResponse", (name) => {
    expect(isDeliveryResponse(fixture(name))).toBe(true);
  });

  it("rejects malformed delivery payloads", () => {
    expect(isDeliveryResponse(null)).toBe(false);
    expect(isDeliveryResponse({ ...fixture<object>("delivery_soften.json"), status: "weird" })).toBe(false);
    expect(isDeliveryResponse({ ...fixture<object>("delivery_soften.json"), workflow: "x" })).toBe(false);
  });

  it("extracts typed structured results per workflow", () => {
    const soften = fixture<DeliveryResponse & { workflow: "soften" }>("delivery_soften.json");
    const decode = fixture<DeliveryResponse & { workflow: "decode" }>("delivery_decode.json");
    const helpSay = fixture<DeliveryResponse & { workflow: "help-say" }>("delivery_help_say.json");

    expect(isSoftenResult(soften.structured_result)).toBe(true);
    expect(isDecodeResult(decode.structured_result)).toBe(true);
    expect(isHelpSayResult(helpSay.structured_result)).toBe(true);

    expect(getStructuredResult(soften)?.rewritten_message).toBe(soften.text);
    expect(getStructuredResult(decode)?.uncertainty).toBe("medium");
    expect(getStructuredResult(helpSay)?.message).toBe(helpSay.text);
  });

  it("returns null structured results for blocked/error or mismatched payloads", () => {
    expect(getStructuredResult(fixture<DeliveryResponse>("delivery_blocked.json"))).toBeNull();
    expect(getStructuredResult(fixture<DeliveryResponse>("delivery_error.json"))).toBeNull();
    const mismatched = { ...fixture<DeliveryResponse>("delivery_soften.json"), workflow: "decode" as const };
    expect(getStructuredResult(mismatched)).toBeNull();
  });
});

describe("consent required", () => {
  const body = {
    error: "consent_required",
    message: "Personal data processing consent is required. Open the Telegram bot and send /start.",
    bot_command: "/start",
  };

  it("matches the ConsentRequiredError schema in docs/openapi.json", () => {
    const spec = JSON.parse(readFileSync(resolve(ROOT, "docs/openapi.json"), "utf-8"));
    const schema = spec.components.schemas.ConsentRequiredError;
    expect(Object.keys(schema.properties).sort()).toEqual(Object.keys(body).sort());
    expect(schema.additionalProperties).toBe(false);
  });

  it("maps the exact 403 body to isConsentRequired", async () => {
    const { fetch } = mockFetch(() => json(body, 403));
    const client = createMiniAppClient({ baseUrl: "http://api", getInitData: () => "init", fetch });
    const error = await client.bootstrap().catch((err: unknown) => err);
    expect(isConsentRequiredError(error)).toBe(true);
    expect((error as MiniAppApiError).status).toBe(403);
    expect((error as MiniAppApiError).detail).toBe(body.message);
    expect((error as MiniAppApiError).body).toEqual(body);
  });

  it("does not treat other 403 bodies as consent required", async () => {
    const { fetch } = mockFetch(() => json({ detail: "Forbidden" }, 403));
    const client = createMiniAppClient({ baseUrl: "http://api", getInitData: () => "init", fetch });
    const error = await client.bootstrap().catch((err: unknown) => err);
    expect(isConsentRequiredError(error)).toBe(false);
  });
});
